name: 'dbt_mta'
version: '1.0.0'

profile: 'dbt_mta'

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  dbt_mta:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
