dbt_mta:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: mta-data-491403
      dataset: mta_warehouse
      location: us-east1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      threads: 4
